apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-workbench" .Values.prefix }}
  namespace: mariahi-lab-workbench
  labels:
    app: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: workbench
          image: quay.apps.hlab.linsoft.local/15ml/lab-workbench@sha256:82f87aacd88a75596745cfbf559de08087df61110a6e2dab4fb47f96abb364a1
          ports:
            - containerPort: 22
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - SYS_CHROOT
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
      imagepullSecrets:
        - name: lab-registry-secret
