apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-workbench" .Values.prefix }}
  namespace: lab-workbench
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: 22
  selector:
    app: workbench