apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-bridge
  labels:
    app: lab-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-bridge
  template:
    metadata:
      labels:
        app: lab-bridge
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: lab-bridge
          image: harbor.15minlab.com/15ml/lab-bridge:latest
          ports:
            - containerPort: 22
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - SYS_CHROOT
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"