apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: { { printf "%s-nginx" .Values.prefix } }
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
