apiVersion: v1
kind: Service
metadata:
  name: workbench
  namespace: {{ printf "%s-nginx" .Values.prefix }}
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: 22
  selector:
    app: workbench